package com.medvet.vetbot.domain;

public enum BotState {
    NEW,
    REG_WAITING_NAME,
    REG_WAITING_PHONE,
    MENU,
    BOOKING_CHOOSING_SERVICE,
    BOOKING_CHOOSING_DATE,
    BOOKING_CHOOSING_TIME,
    BOOKING_WAITING_PET_NAME,
    BOOKING_CHOOSING_PET_TYPE,
    VIEWING_HISTORY,
    EMPLOYEE_MENU,
    EMPLOYEE_VIEWING_BOOKINGS,
    EMPLOYEE_WAITING_SEARCH
}
